apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: docker.io/ramazanzada/admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
