replicaCount: 1

image:
  repository: docker.io/ramazanzada/backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 4000

containerPort: 4000

env:
  - name: NODE_ENV
    value: production
  - name: MONGO_URL
    value: "mongodb+srv://test:emanat1234567@testdevops.ddj33i7.mongodb.net/trendify"
