apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: backend
        image: docker.io/ramazanzada/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URL
          value: "mongodb+srv://test:emanat1234567@testdevops.ddj33i7.mongodb.net/trendify"
